### ISSUE TITLE
In replace of add to cart button, link to bundle products this product is part of

### ISSUE THREAD

**Issue by seb86** [helgatheviking/wc-not-sold-separately#1]
It would be great for customers I think to see how they can get a hold of the item if sold as part of the bundle only by replacing the removed add to cart button with a new button that takes the customer to view the bundle.

That and maybe say that this product is sold as as part of a product bundle only.

**Comment by helgatheviking** [comment]
Good point @seb86 and thanks for the feedback! The problem for me in MNM is that the child product is totally unaware that it's part of a bundle/container. There's no data linking it to it's parent (and it can have multiple parents).

**Comment by seb86** [comment]
What do you think about creating a new meta called `adopted_by` for each item that is added to a bundle @helgatheviking. So when the bundle is saved, if any item added does not already have the meta, add it for the first time. If the item already has the meta, update meta to add to the other product ID's that are also adopting the product.

**Comment by helgatheviking** [comment]
Not sure that's what I'd name the meta key, but the concept yes... that's exactly what would need to happen when the Mix and Match product is saved. 

I'm pretty sure that Product Bundles has a custom table for it's bundled items, so it might be possible to fetch what bundles a product is part of, but a standardized way of doing it would make this plugin more useful. And it would make it possible to display all container/bundle products that a child product is part of.

Part of me wonders if this setting should be on the Mix and Match product instead of on the individual products... then you could mark all the child products as "not sold separately" at one stroke instead of editing each product individually. What do you think? This is easier, but it loses some granular control.

**Comment by helgatheviking** [comment]
This could work as post meta... or potentially a two column lookup table... ie: `container_id` and `child_id`

A note from pgarman regarding queries:

>if you wanted to even REMOVE the not sold products from the catalog, you could do it based on the EXISTENCE of a meta key. and then the VALUE of that key is irrelevant for the "hide from the catalog" filters. but it still remains an efficient query. then you could use the VALUE to say the product ID that the product links back to. this will only be used on the product page or product card linking back to the "pseudo parent" BUT you'll always have pre-primed meta loaded into memory by the time you're interacting with a product so its still fast.
>
>at scale - the combination of two metas into one cuts the meta volume in half. 100k products = 100k metas vs 200k metas.

**Comment by helgatheviking** [comment]
Technically for Mix and Match products that have specific child items (ie using the new custom table) this should be possible. In fact, the MNM data store has a [`query_containers_by_product()` method](https://github.com/kathyisawesome/woocommerce-mix-and-match-products/blob/aed8c1be7ae09a990945adcaf78e6a71f79f00e8/includes/data/class-wc-product-mix-and-match-data-store-cpt.php#L503). Though MNM containers by category would be harder to reverse search.
